name: ♟️ GitHub Chessboard Tracker

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  chessboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd chessboard-visual && npm install

      - name: Run chess animation script
        run: cd chessboard-visual && npm run build
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit SVG board
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "ChessBoard Bot"
          git add chessboard-visual/
          git commit -m "♟️ Update chessboard.svg"
          git push
